databases:
  - name: liberia-business-credit-db

services:
  - type: web
    name: liberia-business-credit-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 180 app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: ChangeMe123!
      - key: DATABASE_URL
        fromDatabase:
          name: liberia-business-credit-db
          property: connectionString
